baseurl: https://yogajia.github.io/
languageCode: zh-cn
title: Yoga's blog! :)
theme: hugo-theme-stack
paginate: 10

defaultContentLanguage: zh-cn
hasCJKLanguage: true

outputs:
  home:
    - RSS
    - JSON

params:
  description: yojia 的个人博客，记录学习与阅读。
  mainSections:
    - post

  author:
    name: yojia
    bio: 个人博客

  sidebar:
    avatar: images/thinking.jpg
    subtitle: loading...

  article:
    math: false
    toc: true
    readingTime: true
    license:
      enabled: false

  comments:
    enabled: true
    provider: giscus
    giscus:
      repo: yogajia/yogajia.github.io
      repoID: R_kgDORlPkaQ
      category: Announcements
      categoryID: DIC_kwDORlPkac4C5w6g
      mapping: pathname
      lightTheme: light
      darkTheme: dark_dimmed
      lang: zh-CN

  widgets:
    homepage:
      - type: search
      - type: archives
        params:
          limit: 5

  colorScheme:
    toggle: true
    default: auto

  imageProcessing:
    cover:
      enabled: true
    content:
      enabled: true

menu:
  main:
    - name: 首页
      url: /
      weight: 1
      params:
        icon: home
    - name: 博客
      url: /archives/
      weight: 2
      params:
        icon: archives
    - name: 相册
      url: /page/gallery/
      weight: 3
      params:
        icon: album
    - name: 关于
      url: /page/about/
      weight: 4
      params:
        icon: user